name = "fixbluesky"
main = "src/index.ts"
compatibility_date = "2023-01-01"

workers_dev = false
route = { pattern = "bsyy.app/*", zone_name = "bsyy.app" }

[vars]
BSKY_SERVICE_URL="https://bsky.social/"
FIXBLUESKY_APP_DOMAIN="bsyy.app"
